// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

public partial class Admin : AppUser
{


    [Column(TypeName = "decimal(18, 2)")]
    public decimal Salary { get; set; }

    [ForeignKey("Id")]

    public virtual AppUser IdNavigation { get; set; }
}