// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Index("CategoryId", Name = "IX_Artisans_CategoryId")]
public partial class Artisan : AppUser
{
    //[Key]
    //public string Id { get; set; }

    [Required]
    public string NationalityId { get; set; }

    [Range(1, 5)]
    public int Rating { get; set; }

    public int CategoryId { get; set; }

    [ForeignKey("CategoryId")]
    public virtual Category Category { get; set; }

    public virtual Contract Contract { get; set; }

    [ForeignKey("Id")]
    public virtual AppUser IdNavigation { get; set; }//important for other classes to work as contract....


    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}