// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Index("CategoryId", Name = "IX_Artisans_CategoryId")]
public partial class Artisan
{
    [Key]
    public string Id { get; set; }

    [Required]
    public string NationalityId { get; set; }

    public int Rating { get; set; }

    public int CategoryId { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Artisans")]
    public virtual Category Category { get; set; }

    [InverseProperty("Artisan")]
    public virtual Contract Contract { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("Artisan")]
    public virtual User IdNavigation { get; set; }

    [InverseProperty("Artisan")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}