// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Table("AuditLog")]
[Index("TableName", Name = "IX_AuditLog_TableName")]
[Index("Timestamp", Name = "IX_AuditLog_Timestamp")]
public partial class AuditLog
{
    [Key]
    public int AuditId { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    [Required]
    [StringLength(100)]
    public string TableName { get; set; }

    public DateTime Timestamp { get; set; }

    [Required]
    public string OldValues { get; set; }

    [Required]
    public string NewValues { get; set; }

    [Required]
    public string AffectedColumns { get; set; }

    [Required]
    public string PrimaryKey { get; set; }
}