// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Table("Contract")]
[Index("ArtisanId", Name = "IX_Contract_ArtisanId", IsUnique = true)]
public partial class Contract
{
    [Key]
    public int Id { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int MaxViolationsAllowed { get; set; }

    [Required]
    public string Status { get; set; }

    [Required]
    public string ArtisanId { get; set; }

    [ForeignKey("ArtisanId")]
    [InverseProperty("Contract")]
    public virtual Artisan Artisan { get; set; }

    [InverseProperty("Contract")]
    public virtual ICollection<Violation> Violations { get; set; } = new List<Violation>();
}