// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Table("Customer")]
public partial class Customer : AppUser
{
    //[Key]
    //public string Id { get; set; }


    public virtual ICollection<CustomerDiscount> CustomerDiscounts { get; set; } = new List<CustomerDiscount>();

    [ForeignKey("Id")]

    public virtual AppUser IdNavigation { get; set; }


    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();


    public virtual ICollection<ServiceRequestPayment> ServiceRequestPayments { get; set; } = new List<ServiceRequestPayment>();
}