// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[PrimaryKey("CustomerId", "DiscountId")]
[Index("DiscountId", Name = "IX_CustomerDiscounts_DiscountId")]
public partial class CustomerDiscount
{
    [Key]
    public string CustomerId { get; set; }

    [Key]
    public int DiscountId { get; set; }

    public DateTime DateGiven { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CustomerDiscounts")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("DiscountId")]
    [InverseProperty("CustomerDiscounts")]
    public virtual Discount Discount { get; set; }
}