// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Table("Discount")]
public partial class Discount
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public int? Amount { get; set; }

    public int? MinRequiredRequests { get; set; }

    public bool? IsFixedAmount { get; set; }

    public bool? IsPercentage { get; set; }

    public DateTime? ExpireDate { get; set; }

    [InverseProperty("Discount")]
    public virtual ICollection<CustomerDiscount> CustomerDiscounts { get; set; } = new List<CustomerDiscount>();
}