// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Table("Review")]
[Index("ArtisanId", Name = "IX_Review_ArtisanId")]
[Index("CustomerId", Name = "IX_Review_CustomerId")]
[Index("ServiceId", Name = "IX_Review_ServiceId")]
public partial class Review
{
    [Key]
    public int Id { get; set; }

    public DateTime ReviewDate { get; set; }

    public int Rating { get; set; }

    [Required]
    public string CustomerId { get; set; }

    [Required]
    public string ArtisanId { get; set; }

    public int ServiceId { get; set; }

    [ForeignKey("ArtisanId")]
    [InverseProperty("Reviews")]
    public virtual Artisan Artisan { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Reviews")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("Reviews")]
    public virtual Service Service { get; set; }

    public string Comment { get; set; }
    public bool isViolate { get; set; } = false;
    public bool isReviewed { get; set; } = false;
}