// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Admin_Dashboard.Enums;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[PrimaryKey("CustomerId", "PaymentId", "ServiceId")]
[Table("ServiceRequestPayment")]
[Index("PaymentId", Name = "IX_ServiceRequestPayment_PaymentId")]
[Index("ServiceId", Name = "IX_ServiceRequestPayment_ServiceId")]
[Index("ArtisanId", Name = "IX_ServiceRequestPayment_ArtisanId")]
public partial class ServiceRequestPayment
{
    [Key]
    public string CustomerId { get; set; }

    [Key]
    public int PaymentId { get; set; }
    [Key]
    public string ArtisanId { get; set; }
    [Key]
    public int ServiceId { get; set; }

    public ServiceRequestStatus Status { get; set; }


    public DateTime CreatedAt { get; set; }

    public int ExecutionTime { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("ServiceRequestPayments")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("ServiceRequestPayments")]
    public virtual Payment Payment { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("ServiceRequestPayments")]
    public virtual Service Service { get; set; }

    [ForeignKey("ArtisanId")]
    public virtual Artisan Artisan { get; set; }}