// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Table("Service")]
[Index("CategoryId", Name = "IX_Service_CategoryId")]
public partial class Service
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string ServiceName { get; set; }

    public double AdditionalPrice { get; set; }

    [Required]
    public string Description { get; set; }

    public double BasePrice { get; set; }

    public int CategoryId { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Services")]
    public virtual Category Category { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [InverseProperty("Service")]
    public virtual ICollection<ServiceRequestPayment> ServiceRequestPayments { get; set; } = new List<ServiceRequestPayment>();
}