// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[PrimaryKey("UserId", "PhoneNumber")]
public partial class UserPhone
{
    [Key]
    public string UserId { get; set; }

    [Key]
    public string PhoneNumber { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserPhones")]
    public virtual AppUser User { get; set; }
}