// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin_Dashboard.Models;

[Table("Violation")]
[Index("ContractId", Name = "IX_Violation_ContractId")]
public partial class Violation
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Reason { get; set; }

    public DateTime Date { get; set; }

    public int ContractId { get; set; }

    [ForeignKey("ContractId")]
    [InverseProperty("Violations")]
    public virtual Contract Contract { get; set; }
}