// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdminDashboard.Models;

[PrimaryKey("PaymentId", "Method")]
public partial class PaymentMethod
{
    [Key]
    public int PaymentId { get; set; }

    [Key]
    public string Method { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("PaymentMethods")]
    public virtual Payment Payment { get; set; }
}