// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdminDashboard.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Status { get; set; }

    public int Amount { get; set; }

    [InverseProperty("Payment")]
    public virtual ICollection<PaymentMethod> PaymentMethods { get; set; } = new List<PaymentMethod>();

    [InverseProperty("Payment")]
    public virtual ICollection<ServiceRequestPayment> ServiceRequestPayments { get; set; } = new List<ServiceRequestPayment>();
}